language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
services:
    - redis-server
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -v JSON"
    - "cpanm -v DateTime"
    - "cpanm -v Test::FailWarnings"
    - "cpanm -v Test::Most"
    - "cpanm -v Devel::Cover::Report::Coveralls"
script:
  perl Makefile.PL && make test && cover -test -report coveralls
