language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
services:
    - redis-server
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -n JSON"
    - "cpanm -n DateTime"
    - "cpanm -n Test::FailWarnings"
    - "cpanm -n Test::Most"
    - "cpanm -n Devel::Cover::Report::Coveralls"
    - mkdir /tmp/old_sereal /tmp/new_sereal
    - (cd /tmp/old_sereal && cpanm -l local -n https://cpan.metacpan.org/authors/id/S/SM/SMUELLER/Sereal-2.011.tar.gz https://cpan.metacpan.org/authors/id/S/SM/SMUELLER/Sereal-Decoder-2.01.tar.gz https://cpan.metacpan.org/authors/id/S/SM/SMUELLER/Sereal-Encoder-2.01.tar.gz)
    - (cd /tmp/new_sereal && cpanm -l local -n https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-3.014.tar.gz https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Decoder-3.014.tar.gz https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Encoder-3.014.tar.gz )
script:
  perl Makefile.PL && make test
